// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Footer from "@/components/Footer";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     // <html
//     //   lang="en"
//     //   className="bg-black text-white"
//     // >
//     //   <body className="min-h-full flex flex-col">{children}</body>
//     //   <body className="min-h-screen flex flex-col">
//     //     {children}
//     //     <Footer />
//     //   </body>
//     // </html>

//     <html lang="en" className="bg-black text-white">
//       <body className="min-h-screen flex flex-col">

//         {/* MAIN CONTENT */}
//         <main className="flex-1">
//           {children}
//         </main>

//         {/* FOOTER */}
//         <Footer />

//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import CustomCursor from "@/components/Customcursor";
// import ThreeBackground from "@/components/ThreeBackground";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "ProjectForge — Engineering Projects",
//   description: "Ready-made and custom engineering projects for students",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <head>
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Syne:wght@700;800;900&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ThreeBackground />
//         <CustomCursor />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import dynamic from "next/dynamic";
import FluidCursor from "@/components/FluidCursor";
import Background from "@/components/Background";
import Footer from "@/components/Footer";

// Heavy visual components — client-only, lazy loaded
// const Background = dynamic(() => import("@/components/Background"), { ssr: false });
// const FluidCursor = dynamic(() => import("@/components/FluidCursor"), { ssr: false });

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProjectForge — Engineering Projects",
  description: "Ready-made and custom engineering projects for students",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* z-index 0 — pure CSS/canvas background, no Three.js */}
        <Background />

        {/* z-index 1 — WebGL fluid simulation, pointer-events:none */}
        <FluidCursor />

        {/* z-index 10+ — all UI content */}
        {children}
        <Footer />
      </body>
    </html>
  );
}